Shop.create(name: "猫カフェMOCHA 池袋西口店", site_url: "http://catmocha.jp/ikebukuro/")
Shop.create(name: "猫カフェMOCHA 京都河原町店", site_url: "http://catmocha.jp/kawaramachi/")
Shop.create(name: "猫カフェMOCHA 名古屋栄店", site_url: "http://catmocha.jp/nagoya/")
Shop.create(name: "猫カフェ モカラウンジ横浜店", site_url: "http://catmocha.jp/yokohama/")
Shop.create(name: "猫カフェMOCHA イオンレイクタウン店", site_url: "http://catmocha.jp/aeonlaketown/")
Shop.create(name: "猫カフェMOCHA 渋谷店", site_url: "http://catmocha.jp/shibuya/")
Shop.create(name: "きゃりこ 新宿店", site_url: "http://catcafe.jp/shop_shinjyuku.html")
Shop.create(name: "らぶねこ", site_url: "http://www.loveneko.jp/access/")
Shop.create(name: "Neko Cafe Keurig", site_url: "http://theloft.nekocafe-keurig.com/")
Shop.create(name: "猫カフェ〜美猫〜", site_url: "https://minatoneko.wixsite.com/bineko/")

Cat.create(name: "むぅ", shop_id: 1)
Cat.create(name: "ジュジュ", shop_id: 1)
Cat.create(name: "桜", shop_id: 1)
Cat.create(name: "金太郎", shop_id: 2)
Cat.create(name: "ラン", shop_id: 2)
Cat.create(name: "ハンサム", shop_id: 3)
Cat.create(name: "みらい", shop_id: 3)
Cat.create(name: "もみじ", shop_id: 5)
Cat.create(name: "オレオ", shop_id: 5)
Cat.create(name: "ぼたん", shop_id: 5)
Cat.create(name: "もずく", shop_id: 6)
Cat.create(name: "正宗", shop_id: 1)
Cat.create(name: "もんじゃ", shop_id: 1)
Cat.create(name: "シッポコ", shop_id: 2)
Cat.create(name: "パン", shop_id: 2)
Cat.create(name: "殿", shop_id: 2)
Cat.create(name: "みこし", shop_id: 7)
Cat.create(name: "コタロー", shop_id: 8)
Cat.create(name: "ミッチェル", shop_id: 8)
Cat.create(name: "ウィン", shop_id: 8)
Cat.create(name: "杏仁", shop_id: 8)
Cat.create(name: "乙姫", shop_id: 10)
Cat.create(name: "くるみ", shop_id: 10)
Cat.create(name: "佐助", shop_id: 10)
Cat.create(name: "ささみ", shop_id: 10)

Post.create(user_id: 1, cat_id: 1)
Post.create(user_id: 1, cat_id: 2)
Post.create(user_id: 1, cat_id: 3)
Post.create(user_id: 1, cat_id: 4)
Post.create(user_id: 1, cat_id: 5)
Post.create(user_id: 1, cat_id: 6)
Post.create(user_id: 1, cat_id: 7)
Post.create(user_id: 1, cat_id: 8)
Post.create(user_id: 1, cat_id: 9)
Post.create(user_id: 1, cat_id: 10)
Post.create(user_id: 1, cat_id: 11)
Post.create(user_id: 1, cat_id: 12)
Post.create(user_id: 1, cat_id: 13)
Post.create(user_id: 1, cat_id: 14)
Post.create(user_id: 1, cat_id: 15)
Post.create(user_id: 1, cat_id: 16)
Post.create(user_id: 1, cat_id: 17)
Post.create(user_id: 1, cat_id: 18)
Post.create(user_id: 1, cat_id: 19)
Post.create(user_id: 1, cat_id: 20)
Post.create(user_id: 1, cat_id: 21)
Post.create(user_id: 1, cat_id: 22)
Post.create(user_id: 1, cat_id: 23)
Post.create(user_id: 1, cat_id: 24)
Post.create(user_id: 1, cat_id: 25)

Image.create(post_id: 1, image_path: "0001.jpg")
Image.create(post_id: 2, image_path: "0002.jpg")
Image.create(post_id: 3, image_path: "0003.jpg")
Image.create(post_id: 4, image_path: "0004.jpg")
Image.create(post_id: 5, image_path: "0005.jpg")
Image.create(post_id: 6, image_path: "0006.jpg")
Image.create(post_id: 7, image_path: "0007.jpg")
Image.create(post_id: 8, image_path: "0008.jpg")
Image.create(post_id: 9, image_path: "0009.jpg")
Image.create(post_id: 10, image_path: "0010.jpg")
Image.create(post_id: 11, image_path: "0011.jpg")
Image.create(post_id: 12, image_path: "0012.jpg")
Image.create(post_id: 13, image_path: "0013.jpg")
Image.create(post_id: 14, image_path: "0014.jpg")
Image.create(post_id: 15, image_path: "0015.jpg")
Image.create(post_id: 16, image_path: "0016.jpg")
Image.create(post_id: 17, image_path: "0017.jpg")
Image.create(post_id: 18, image_path: "0018.jpg")
Image.create(post_id: 19, image_path: "0019.jpg")
Image.create(post_id: 20, image_path: "0020.jpg")
Image.create(post_id: 21, image_path: "0021.jpg")
Image.create(post_id: 22, image_path: "0022.jpg")
Image.create(post_id: 23, image_path: "0023.jpg")
Image.create(post_id: 24, image_path: "0024.jpg")
Image.create(post_id: 25, image_path: "0025.jpg")


User.create(name: "yuuis", email: "hoge@example.com")

PasswordAuthentication.create(password_digest: "hoge", user_id: 1)